# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  # workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true 
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

    - name: update submodules up to date
      run: git submodule foreach git pull origin master

    - name: check if something changed
      uses: dorny/paths-filter@v2.2.1
      id: filter
      with:
        base: 'main'        
        filters: |
          docs:
            - 'exampleSite/**'

    - name: Setup Hugo
      run: |
          sudo snap remove hugo
          sudo snap install hugo
      
    - name: Git init
      run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'

    - name: Build hugo
      run: ./build_docs.sh

    - name: Git branch
      run: |
        git checkout publish || git checkout -b publish
      
    - name: Git add 
      run: git add --force .

    - name: Git commit
      run: git commit -m "publish"

    - name: Push public to branch
      run: |
          git push -f origin publish
